-- =====================================================
-- ISLAND CHAT — Storage bucket for photos & voice notes
-- Run this ONCE in Supabase → SQL Editor → New Query
-- =====================================================
--
-- Per-user quota (enforced client-side + server cap):
--   • 5 photos per user (auto-compressed to ~150 KB JPEG, 1024px max)
--   • 10 voice notes per user (~80 KB each)
-- Estimated ceiling for 1,000,000 users: ~1.5 TB.
-- Older files are rotated out automatically when a user exceeds the cap.
-- Messages are already ephemeral (24h TTL), so real usage is far lower.
--
-- Folder layout enforced by RLS:
--   {auth.uid()}/photos/<file>.jpg
--   {auth.uid()}/voice/<file>.m4a
--
-- Bucket is PRIVATE. Clients access media via short-lived signed URLs
-- generated on-demand (see expo/lib/mediaStorage.ts → getSignedMediaUrl).
-- =====================================================

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'chat-media',
  'chat-media',
  false,
  2 * 1024 * 1024,
  array['image/jpeg','image/png','image/webp','audio/mp4','audio/mpeg','audio/webm','audio/aac','audio/wav']
)
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- READ — only authenticated users can read. Signed URLs bypass RLS,
-- so unauthenticated users can still view an image via a short-lived
-- signed URL (1h TTL) generated by another signed-in user.
drop policy if exists "chat-media public read" on storage.objects;
drop policy if exists "chat-media read" on storage.objects;
drop policy if exists "chat-media authenticated read" on storage.objects;
create policy "chat-media authenticated read"
  on storage.objects for select
  to authenticated
  using (bucket_id = 'chat-media');

-- INSERT — only into your own {uid}/photos/* or {uid}/voice/* folder
drop policy if exists "chat-media insert" on storage.objects;
drop policy if exists "chat-media insert own" on storage.objects;
create policy "chat-media insert own"
  on storage.objects for insert
  to authenticated
  with check (
    bucket_id = 'chat-media'
    and auth.uid()::text = (storage.foldername(name))[1]
    and (storage.foldername(name))[2] in ('photos', 'voice')
  );

-- UPDATE — only your own files
drop policy if exists "chat-media update" on storage.objects;
drop policy if exists "chat-media update own" on storage.objects;
create policy "chat-media update own"
  on storage.objects for update
  to authenticated
  using (
    bucket_id = 'chat-media'
    and auth.uid()::text = (storage.foldername(name))[1]
  )
  with check (
    bucket_id = 'chat-media'
    and auth.uid()::text = (storage.foldername(name))[1]
  );

-- DELETE — only your own files
drop policy if exists "chat-media delete" on storage.objects;
drop policy if exists "chat-media delete own" on storage.objects;
create policy "chat-media delete own"
  on storage.objects for delete
  to authenticated
  using (
    bucket_id = 'chat-media'
    and auth.uid()::text = (storage.foldername(name))[1]
  );
